export default [
  {
    _id: 'bitcoin@bitcoin',
    asset: 'bitcoin',
    platform: 'bitcoin',
    type: 'coin',
    name: 'Bitcoin',
    symbol: 'BTC',
    decimals: 8,
    logo: 'bitcoin.svg',
    coingecko: {
      id: 'bitcoin',
    },
    meta: {
      rank: 1,
      popular: 1,
      new: 1,
    },
  },
  {
    _id: 'ethereum@ethereum',
    asset: 'ethereum',
    platform: 'ethereum',
    type: 'coin',
    name: 'Ethereum',
    symbol: 'ETH',
    decimals: 18,
    logo: 'ethereum.svg',
    coingecko: {
      id: 'ethereum',
    },
    meta: {
      rank: 2,
      popular: 2,
      new: 2,
    },
  },
  {
    _id: 'polygon@polygon',
    asset: 'polygon',
    platform: 'polygon',
    type: 'coin',
    name: 'Polygon',
    symbol: 'POL',
    decimals: 18,
    logo: 'polygon.svg',
    coingecko: {
      id: 'polygon-ecosystem-token',
    },
    meta: {
      rank: 3,
      popular: 3,
      new: 3,
    },
  },
  {
    _id: 'tron@tron',
    asset: 'tron',
    platform: 'tron',
    type: 'coin',
    name: 'Tron',
    symbol: 'TRX',
    decimals: 6,
    logo: 'tron.svg',
    coingecko: {
      id: 'tron',
    },
    meta: {
      rank: 4,
      popular: 4,
      new: 4,
    },
  },
  {
    _id: 'tether@ethereum',
    asset: 'tether',
    platform: 'ethereum',
    type: 'token',
    name: 'Tether',
    symbol: 'USDT',
    address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
    decimals: 6,
    logo: 'tether.svg',
    coingecko: {
      id: 'tether',
    },
    meta: {
      rank: 5,
    },
  },
  {
    _id: 'usd-coin@ethereum',
    asset: 'usd-coin',
    platform: 'ethereum',
    type: 'token',
    name: 'USDC',
    symbol: 'USDC',
    address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    decimals: 6,
    logo: 'usd-coin.svg',
    coingecko: {
      id: 'usd-coin',
    },
    meta: {
      rank: 6,
    },
  },
  {
    _id: 'dai@ethereum',
    asset: 'dai',
    platform: 'ethereum',
    type: 'token',
    name: 'Dai',
    symbol: 'DAI',
    address: '0x6b175474e89094c44da98b954eedeac495271d0f',
    decimals: 18,
    logo: 'dai.svg',
    coingecko: {
      id: 'dai',
    },
    meta: {
      rank: 7,
    },
  },
  {
    _id: 'wrapped-bitcoin@ethereum',
    asset: 'wrapped-bitcoin',
    platform: 'ethereum',
    type: 'token',
    name: 'Wrapped Bitcoin',
    symbol: 'WBTC',
    address: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
    decimals: 8,
    logo: 'wrapped-bitcoin.svg',
    coingecko: {
      id: 'wrapped-bitcoin',
    },
    meta: {
      rank: 8,
    },
  },
  {
    _id: 'chainlink@ethereum',
    asset: 'chainlink',
    platform: 'ethereum',
    type: 'token',
    name: 'Chainlink',
    symbol: 'LINK',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    decimals: 18,
    logo: 'chainlink.svg',
    coingecko: {
      id: 'chainlink',
    },
    meta: {
      rank: 9,
    },
  },
  {
    _id: 'uniswap@ethereum',
    asset: 'uniswap',
    platform: 'ethereum',
    type: 'token',
    name: 'Uniswap',
    symbol: 'UNI',
    address: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984',
    decimals: 18,
    logo: 'uniswap.svg',
    coingecko: {
      id: 'uniswap',
    },
    meta: {
      rank: 10,
    },
  },
  {
    _id: 'tether@polygon',
    asset: 'tether',
    platform: 'polygon',
    type: 'token',
    name: 'Tether',
    symbol: 'USDT',
    address: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
    decimals: 6,
    logo: 'tether.svg',
    coingecko: {
      id: 'tether',
    },
    meta: {
      rank: 11,
    },
  },
  {
    _id: 'usd-coin@polygon',
    asset: 'usd-coin',
    platform: 'polygon',
    type: 'token',
    name: 'USDC',
    symbol: 'USDC',
    address: '0x3c499c542cef5e3811e1192ce70d8cc03d5c3359',
    decimals: 6,
    logo: 'usd-coin.svg',
    coingecko: {
      id: 'usd-coin',
    },
    meta: {
      rank: 12,
    },
  },
  {
    _id: 'dai@polygon',
    asset: 'dai',
    platform: 'polygon',
    type: 'token',
    name: 'Dai',
    symbol: 'DAI',
    address: '0x8f3cf7ad23cd3cadbd9735aff958023239c6a063',
    decimals: 18,
    logo: 'dai.svg',
    coingecko: {
      id: 'dai',
    },
    meta: {
      rank: 13,
    },
  },
  {
    _id: 'chainlink@polygon',
    asset: 'chainlink',
    platform: 'polygon',
    type: 'token',
    name: 'Chainlink',
    symbol: 'LINK',
    address: '0x53e0bca35ec356bd5dddfebbd1fc0fd03fabad39',
    decimals: 18,
    logo: 'chainlink.svg',
    coingecko: {
      id: 'chainlink',
    },
    meta: {
      rank: 14,
    },
  },
  {
    _id: 'uniswap@polygon',
    asset: 'uniswap',
    platform: 'polygon',
    type: 'token',
    name: 'Uniswap',
    symbol: 'UNI',
    address: '0xb33eaad8d922b1083446dc23f610c2567fb5180f',
    decimals: 18,
    logo: 'uniswap.svg',
    coingecko: {
      id: 'uniswap',
    },
    meta: {
      rank: 15,
    },
  },
  {
    _id: 'tether@tron',
    asset: 'tether',
    platform: 'tron',
    type: 'token',
    name: 'Tether',
    symbol: 'USDT',
    address: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
    decimals: 6,
    logo: 'tether.svg',
    coingecko: {
      id: 'tether',
    },
    meta: {
      rank: 16,
    },
  },
  {
    _id: 'usd-coin@tron',
    asset: 'usd-coin',
    platform: 'tron',
    type: 'token',
    name: 'USDC',
    symbol: 'USDC',
    address: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
    decimals: 6,
    logo: 'usd-coin.svg',
    coingecko: {
      id: 'usd-coin',
    },
    meta: {
      rank: 17,
    },
  },
  {
    _id: 'usdd@tron',
    asset: 'usdd',
    platform: 'tron',
    type: 'token',
    name: 'USDD',
    symbol: 'USDD',
    address: 'TXDk8mbtRbXeYuMNS83CfKPaYYT8XWv9Hz',
    decimals: 18,
    logo: 'usdd.svg',
    coingecko: {
      id: 'usdd',
    },
    meta: {
      rank: 18,
    },
  },
];
